"""
Django settings for PRIMA project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = 'wajuj-%@)(olkjnuu^#sadasdasd@6hk=@p37zx(u4xn2'

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'PRIMA-BUS.RU',"10.1.193.253"]


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, 'db.sqlite3')
    }
}

# Static file

STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [ STATIC_DIR ]
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
