# Generated by Django 3.1.4 on 2021-01-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201220_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvtoPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('large', models.TextField(verbose_name='Количество сидячих')),
                ('poster', models.ImageField(upload_to='service/', verbose_name='Картинка')),
                ('prelog', models.TextField(verbose_name='Описание c многоточием в оглавлении')),
                ('price', models.PositiveIntegerField(default=0, help_text='Указываем сумму!*ПУК*', verbose_name='Цена')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'АвтоПарк',
                'verbose_name_plural': 'Авто Праки',
            },
        ),
    ]
