# Generated by Django 3.1.4 on 2021-01-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avtopark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сustomers',
            name='url',
        ),
        migrations.AlterField(
            model_name='avtopark',
            name='prelog',
            field=models.TextField(verbose_name='Пункт'),
        ),
    ]
