# Generated by Django 3.1.4 on 2021-01-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210106_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Avto/', verbose_name='Изображение')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.avtopark', verbose_name='Авто парк')),
            ],
            options={
                'verbose_name': ' ',
                'verbose_name_plural': 'Дополнительные фото',
            },
        ),
    ]
