# Generated by Django 3.1.4 on 2021-01-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clothesshots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothesshots',
            old_name='clothes',
            new_name='avto',
        ),
        migrations.AddField(
            model_name='clothesshots',
            name='disc1',
            field=models.CharField(default='sda', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothesshots',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Указываем сумму!*ПУК*', verbose_name='Цена'),
        ),
    ]
