# Generated by Django 3.1.4 on 2021-01-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210107_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothesShots',
            new_name='AvtoExample',
        ),
    ]
