# Generated by Django 3.1.4 on 2021-01-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210107_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avtopark',
            name='large',
        ),
        migrations.RemoveField(
            model_name='avtopark',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='avtopark',
            name='prelog',
        ),
        migrations.RemoveField(
            model_name='avtopark',
            name='price',
        ),
    ]
