# Generated by Django 3.1.4 on 2021-01-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210109_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avtoexample',
            options={'verbose_name': 'Авто-парк экземляр', 'verbose_name_plural': 'Авто-парк экземпляры'},
        ),
        migrations.AddField(
            model_name='avtoexample',
            name='disc',
            field=models.CharField(default='sdas', max_length=100, verbose_name='Имя автобаса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avtoexample',
            name='disc2',
            field=models.CharField(default='sdasd', max_length=100, verbose_name='Кондиционер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avtoexample',
            name='disc1',
            field=models.CharField(max_length=100, verbose_name='Багажное отделение'),
        ),
        migrations.AlterField(
            model_name='avtoexample',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название автобуса/трам...'),
        ),
    ]
