# Generated by Django 3.1.4 on 2021-01-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210109_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='transports/', verbose_name='Картинка')),
                ('prelog', models.TextField(verbose_name='Описание c многоточием в оглавлении')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Перевозка',
                'verbose_name_plural': 'Перевозки',
            },
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Указываем сумму.', verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Указываем сумму.', verbose_name='Цена'),
        ),
    ]
