# Generated by Django 3.1.4 on 2021-01-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtopark',
            name='image',
            field=models.ImageField(default='set', upload_to='News/', verbose_name='Првеью новости'),
            preserve_default=False,
        ),
    ]
